### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by pzfreo** [weaveworks/weave-gitops-private#3]
**Short description**
As a wego user I want to know if there is a newer version so that I can download it.

**Acceptance criteria**
- [ ] calls checkpoint with various data
- [ ] checks if there is a newer version
- [ ] displays the latest version if it exists

**Design materials**
https://github.com/weaveworks/go-checkpoint

**Work breakdown**
